# Generated by Django 4.1.4 on 2023-01-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='nots',
        ),
        migrations.AddField(
            model_name='missiontimesheet',
            name='nots',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
    ]
