# Generated by Django 3.2.16 on 2023-01-26 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studens', '0002_remove_mission_nots_missiontimesheet_nots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الإنشاء بواسطة'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='is_mission_close',
            field=models.BooleanField(default=False, verbose_name='انتهت المهمة ؟'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='التعديل بواسطة'),
        ),
    ]
